/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

void main()
{
object oPC;

oPC = GetItemActivator();

effect eEffect;
eEffect = EffectSummonCreature("petrock", VFX_COM_CHUNK_STONE_MEDIUM, 1.0);

ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eEffect, oPC, 60.0);

}

