#!/usr/bin/env python3
"""Build gate: the tree must match the season block in server.env.

Every season-scoped string in this repo — the module description's connect and
wiki lines, the guide/merit NPC links, the login floaty text, the Well of Eru
signs, the worker name and redirect, and (from season 2 on) the module and
server names — is generated by bin/season-brand.py from server.env's SEASON_*
block. Hand-editing any of them, or editing the season block without re-running
the script, silently ships a module that advertises the wrong wiki, the wrong
port, or an early-access wipe warning on the live season.

This gate makes that unpackable: it runs `season-brand.py --check` and fails the
repack until `--apply` has been run. Same idea as check_palette_coverage for
blueprints.

Exit 0 = in sync, 1 = drifted (or the script errored).
"""
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BRAND = REPO / "bin" / "season-brand.py"


def main() -> int:
    if not BRAND.exists():
        print(f"FAIL season-brand: {BRAND} is missing")
        return 1

    proc = subprocess.run(
        [sys.executable, str(BRAND), "--check"],
        capture_output=True, text=True, cwd=str(REPO),
    )
    out = (proc.stdout + proc.stderr).strip()

    if proc.returncode == 0:
        # First line carries the resolved season identity — worth showing, since
        # a repack of the wrong season is otherwise invisible in the log.
        first = out.splitlines()[0] if out else ""
        print(f"ok season-brand: {first}")
        return 0

    print("FAIL season-brand: the tree has drifted from the season block in server.env")
    for line in out.splitlines():
        print(f"       {line}")
    print("       fix: python3 bin/season-brand.py --apply")
    return 1


if __name__ == "__main__":
    sys.exit(main())
