#!/usr/bin/env python3
"""Manual-page nav menu directives check (build-time smoke test).

Pages in docs.manual/ land in the wiki's "Documents" nav dropdown by default. A page
can override that with an `@menu 'Name'` directive in its source, which the wiki build
finds by regex-scanning the raw file text (see _RE_MANUAL_MENU in nwn_manager/bin/nwn-wiki).

Two of our pages depend on that override, and one of them has silently lost it before:

  * docs.manual/Roadmap.html is regenerated wholesale by bin/gen-roadmap.py. On 2026-07-17
    the directive was hand-added to the *output* (247e83362cb) and the very next roadmap
    regeneration deleted it again (0bd72181750), dropping Roadmap back into Documents with
    nothing to signal it. The directive now lives in gen-roadmap.py's HTML template, which
    is the only place it survives a regeneration.
  * docs.manual/QuestGuide.html declares @menu 'Quests' so it shares a dropdown with the
    generated Journal Entries page. Without it the Quests nav entry collapses back to a
    plain single link (that fallback is deliberate and module-agnostic — see _quests_nav).

This gate asserts each page below still declares the menu it needs, so a third silent
regression fails the build instead of quietly changing the wiki's navigation.

Exits 0 on success, 1 on any failure.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANUAL = os.path.join(ROOT, "docs.manual")

# Manual page -> the nav menu it must declare via @menu.
EXPECTED = {
    "Roadmap.html": "Activity",
    "QuestGuide.html": "Quests",
}

# Why a page's directive can go missing — printed with the failure so the fix is obvious.
HINTS = {
    "Roadmap.html": (
        "This file is regenerated by bin/gen-roadmap.py — the directive must live in that "
        "script's HTML template, not be hand-added to the output, or the next regeneration "
        "wipes it (as happened in 0bd72181750)."
    ),
}

# Mirrors _RE_MANUAL_MENU in nwn_manager/bin/nwn-wiki, so this gate can never disagree
# with the generator about what counts as a directive.
RE_MENU = re.compile(r"@menu\s+(?:'([^']*)'|\"([^\"]*)\"|([^\n]+))", re.IGNORECASE)


def declared_menu(text):
    """The @menu name declared in a page's source, or None when absent."""
    m = RE_MENU.search(text)
    if not m:
        return None
    return (m.group(1) or m.group(2) or m.group(3) or "").strip() or None


def main():
    failures = []

    for filename, expected in sorted(EXPECTED.items()):
        path = os.path.join(MANUAL, filename)
        if not os.path.isfile(path):
            failures.append((filename, f"docs.manual/{filename} is missing"))
            continue

        with open(path, encoding="utf-8") as fh:
            found = declared_menu(fh.read())

        if found is None:
            failures.append((filename, f"no @menu directive — expected @menu '{expected}'"))
        elif found != expected:
            failures.append(
                (filename, f"declares @menu '{found}' — expected @menu '{expected}'"))

    if failures:
        print("manual nav menu check FAILED:")
        for filename, problem in failures:
            print(f"  {filename}: {problem}")
            if filename in HINTS:
                print(f"    {HINTS[filename]}")
        return 1

    print(f"manual nav menu check OK: {len(EXPECTED)} pages declare their nav menu.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
