export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // GENERATED by bin/season-brand.py from the season block in server.env.
    // Do not hand-edit — `season-brand.py --check` is a repack build gate.
    //
    // CANONICAL      this environment's own wiki host.
    // REDIRECT_HOSTS hosts that 301 to it. Non-empty only while this season is
    //                LIVE, where it holds season<N>.homerslotr.com: the apex is
    //                the live season's address, so its own season subdomain
    //                folds into it rather than serving a duplicate site. When
    //                this season is archived the list empties again and
    //                season<N>. goes back to serving its frozen wiki, which is
    //                what the cutover guide's "one worker per season,
    //                permanently bound" rule promises.
    const CANONICAL = 'season1.homerslotr.com';
    const REDIRECT_HOSTS = [];

    // Legacy *.workers.dev URLs always fold into the canonical host.
    if (url.hostname.endsWith('.workers.dev') || REDIRECT_HOSTS.includes(url.hostname)) {
      url.hostname = CANONICAL;
      return Response.redirect(url.toString(), 301);
    }

    // Otherwise serve the static asset as normal
    return env.ASSETS.fetch(request);
  }
};
